version: 2
updates:
  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # Labels on pull requests for version updates only
    labels:
      - "pip dependencies"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
