# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat

from six import iteritems


class CodeVersionPK(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'str',
        'codebase_ref': 'CodeBaseRef'
    }

    attribute_map = {
        'version': 'version',
        'codebase_ref': 'codebaseRef'
    }

    def __init__(self, version=None, codebase_ref=None):
        """
        CodeVersionPK - a model defined in Swagger
        """

        self._version = None
        self._codebase_ref = None

        self.version = version
        self.codebase_ref = codebase_ref

    @property
    def version(self):
        """
        Gets the version of this CodeVersionPK.
        unique id, e.g. git commit hash.

        :return: The version of this CodeVersionPK.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this CodeVersionPK.
        unique id, e.g. git commit hash.

        :param version: The version of this CodeVersionPK.
        :type: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")

        self._version = version

    @property
    def codebase_ref(self):
        """
        Gets the codebase_ref of this CodeVersionPK.
        indicates the code base where given code version belongs to

        :return: The codebase_ref of this CodeVersionPK.
        :rtype: CodeBaseRef
        """
        return self._codebase_ref

    @codebase_ref.setter
    def codebase_ref(self, codebase_ref):
        """
        Sets the codebase_ref of this CodeVersionPK.
        indicates the code base where given code version belongs to

        :param codebase_ref: The codebase_ref of this CodeVersionPK.
        :type: CodeBaseRef
        """
        if codebase_ref is None:
            raise ValueError("Invalid value for `codebase_ref`, must not be `None`")

        self._codebase_ref = codebase_ref

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CodeVersionPK):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
