# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat

from six import iteritems


class CodeVersion(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pk': 'CodeVersionPK',
        'maintainers_refs': 'list[UserRef]'
    }

    attribute_map = {
        'pk': 'pk',
        'maintainers_refs': 'maintainersRefs'
    }

    def __init__(self, pk=None, maintainers_refs=None):
        """
        CodeVersion - a model defined in Swagger
        """

        self._pk = None
        self._maintainers_refs = None

        self.pk = pk
        self.maintainers_refs = maintainers_refs

    @property
    def pk(self):
        """
        Gets the pk of this CodeVersion.

        :return: The pk of this CodeVersion.
        :rtype: CodeVersionPK
        """
        return self._pk

    @pk.setter
    def pk(self, pk):
        """
        Sets the pk of this CodeVersion.

        :param pk: The pk of this CodeVersion.
        :type: CodeVersionPK
        """
        if pk is None:
            raise ValueError("Invalid value for `pk`, must not be `None`")

        self._pk = pk

    @property
    def maintainers_refs(self):
        """
        Gets the maintainers_refs of this CodeVersion.
        list of the code version maintainers

        :return: The maintainers_refs of this CodeVersion.
        :rtype: list[UserRef]
        """
        return self._maintainers_refs

    @maintainers_refs.setter
    def maintainers_refs(self, maintainers_refs):
        """
        Sets the maintainers_refs of this CodeVersion.
        list of the code version maintainers

        :param maintainers_refs: The maintainers_refs of this CodeVersion.
        :type: list[UserRef]
        """
        if maintainers_refs is None:
            raise ValueError("Invalid value for `maintainers_refs`, must not be `None`")

        self._maintainers_refs = maintainers_refs

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CodeVersion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
