# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat

from six import iteritems


class DataSourcePK(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'location': 'str',
        'physical_location_ref': 'PhysicalLocationRef'
    }

    attribute_map = {
        'location': 'location',
        'physical_location_ref': 'physicalLocationRef'
    }

    def __init__(self, location=None, physical_location_ref=None):
        """
        DataSourcePK - a model defined in Swagger
        """

        self._location = None
        self._physical_location_ref = None

        self.location = location
        self.physical_location_ref = physical_location_ref

    @property
    def location(self):
        """
        Gets the location of this DataSourcePK.
        fully qualified location of the datasource, must be unique

        :return: The location of this DataSourcePK.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """
        Sets the location of this DataSourcePK.
        fully qualified location of the datasource, must be unique

        :param location: The location of this DataSourcePK.
        :type: str
        """
        if location is None:
            raise ValueError("Invalid value for `location`, must not be `None`")

        self._location = location

    @property
    def physical_location_ref(self):
        """
        Gets the physical_location_ref of this DataSourcePK.
        Physical location where the Datasource is stored

        :return: The physical_location_ref of this DataSourcePK.
        :rtype: PhysicalLocationRef
        """
        return self._physical_location_ref

    @physical_location_ref.setter
    def physical_location_ref(self, physical_location_ref):
        """
        Sets the physical_location_ref of this DataSourcePK.
        Physical location where the Datasource is stored

        :param physical_location_ref: The physical_location_ref of this DataSourcePK.
        :type: PhysicalLocationRef
        """
        if physical_location_ref is None:
            raise ValueError("Invalid value for `physical_location_ref`, must not be `None`")

        self._physical_location_ref = physical_location_ref

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DataSourcePK):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
