# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat

from six import iteritems


class DataStatsPK(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'schema_ref': 'SchemaRef',
        'lineage_run_ref': 'LineageRunRef'
    }

    attribute_map = {
        'schema_ref': 'schemaRef',
        'lineage_run_ref': 'lineageRunRef'
    }

    def __init__(self, schema_ref=None, lineage_run_ref=None):
        """
        DataStatsPK - a model defined in Swagger
        """

        self._schema_ref = None
        self._lineage_run_ref = None

        self.schema_ref = schema_ref
        self.lineage_run_ref = lineage_run_ref

    @property
    def schema_ref(self):
        """
        Gets the schema_ref of this DataStatsPK.
        Points to the data

        :return: The schema_ref of this DataStatsPK.
        :rtype: SchemaRef
        """
        return self._schema_ref

    @schema_ref.setter
    def schema_ref(self, schema_ref):
        """
        Sets the schema_ref of this DataStatsPK.
        Points to the data

        :param schema_ref: The schema_ref of this DataStatsPK.
        :type: SchemaRef
        """
        if schema_ref is None:
            raise ValueError("Invalid value for `schema_ref`, must not be `None`")

        self._schema_ref = schema_ref

    @property
    def lineage_run_ref(self):
        """
        Gets the lineage_run_ref of this DataStatsPK.
        Points to the lineage run which processes the data

        :return: The lineage_run_ref of this DataStatsPK.
        :rtype: LineageRunRef
        """
        return self._lineage_run_ref

    @lineage_run_ref.setter
    def lineage_run_ref(self, lineage_run_ref):
        """
        Sets the lineage_run_ref of this DataStatsPK.
        Points to the lineage run which processes the data

        :param lineage_run_ref: The lineage_run_ref of this DataStatsPK.
        :type: LineageRunRef
        """
        if lineage_run_ref is None:
            raise ValueError("Invalid value for `lineage_run_ref`, must not be `None`")

        self._lineage_run_ref = lineage_run_ref

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DataStatsPK):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
