# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat

from six import iteritems


class FieldDef(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'field_type': 'str',
        'nullable': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'field_type': 'fieldType',
        'nullable': 'nullable'
    }

    def __init__(self, name=None, field_type=None, nullable=None):
        """
        FieldDef - a model defined in Swagger
        """

        self._name = None
        self._field_type = None
        self._nullable = None

        self.name = name
        self.field_type = field_type
        self.nullable = nullable

    @property
    def name(self):
        """
        Gets the name of this FieldDef.

        :return: The name of this FieldDef.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this FieldDef.

        :param name: The name of this FieldDef.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def field_type(self):
        """
        Gets the field_type of this FieldDef.

        :return: The field_type of this FieldDef.
        :rtype: str
        """
        return self._field_type

    @field_type.setter
    def field_type(self, field_type):
        """
        Sets the field_type of this FieldDef.

        :param field_type: The field_type of this FieldDef.
        :type: str
        """
        if field_type is None:
            raise ValueError("Invalid value for `field_type`, must not be `None`")

        self._field_type = field_type

    @property
    def nullable(self):
        """
        Gets the nullable of this FieldDef.

        :return: The nullable of this FieldDef.
        :rtype: bool
        """
        return self._nullable

    @nullable.setter
    def nullable(self, nullable):
        """
        Sets the nullable of this FieldDef.

        :param nullable: The nullable of this FieldDef.
        :type: bool
        """
        if nullable is None:
            raise ValueError("Invalid value for `nullable`, must not be `None`")

        self._nullable = nullable

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, FieldDef):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
