# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: develop
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProcessRunMetrics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pk': 'ProcessRunMetricsPK',
        'metrics': 'dict(str, float)',
        'options': 'dict(str, str)'
    }

    attribute_map = {
        'pk': 'pk',
        'metrics': 'metrics',
        'options': 'options'
    }

    def __init__(self, pk=None, metrics=None, options=None):  # noqa: E501
        """ProcessRunMetrics - a model defined in Swagger"""  # noqa: E501
        self._pk = None
        self._metrics = None
        self._options = None
        self.discriminator = None
        self.pk = pk
        self.metrics = metrics
        self.options = options

    @property
    def pk(self):
        """Gets the pk of this ProcessRunMetrics.  # noqa: E501


        :return: The pk of this ProcessRunMetrics.  # noqa: E501
        :rtype: ProcessRunMetricsPK
        """
        return self._pk

    @pk.setter
    def pk(self, pk):
        """Sets the pk of this ProcessRunMetrics.


        :param pk: The pk of this ProcessRunMetrics.  # noqa: E501
        :type: ProcessRunMetricsPK
        """
        if pk is None:
            raise ValueError("Invalid value for `pk`, must not be `None`")  # noqa: E501

        self._pk = pk

    @property
    def metrics(self):
        """Gets the metrics of this ProcessRunMetrics.  # noqa: E501


        :return: The metrics of this ProcessRunMetrics.  # noqa: E501
        :rtype: dict(str, float)
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics):
        """Sets the metrics of this ProcessRunMetrics.


        :param metrics: The metrics of this ProcessRunMetrics.  # noqa: E501
        :type: dict(str, float)
        """
        if metrics is None:
            raise ValueError("Invalid value for `metrics`, must not be `None`")  # noqa: E501

        self._metrics = metrics

    @property
    def options(self):
        """Gets the options of this ProcessRunMetrics.  # noqa: E501


        :return: The options of this ProcessRunMetrics.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this ProcessRunMetrics.


        :param options: The options of this ProcessRunMetrics.  # noqa: E501
        :type: dict(str, str)
        """
        if options is None:
            raise ValueError("Invalid value for `options`, must not be `None`")  # noqa: E501

        self._options = options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProcessRunMetrics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProcessRunMetrics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
