# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat

from six import iteritems


class ProcessRunPK(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'process_ref': 'ProcessRef',
        'qualified_name': 'str'
    }

    attribute_map = {
        'process_ref': 'processRef',
        'qualified_name': 'qualifiedName'
    }

    def __init__(self, process_ref=None, qualified_name=None):
        """
        ProcessRunPK - a model defined in Swagger
        """

        self._process_ref = None
        self._qualified_name = None

        self.process_ref = process_ref
        self.qualified_name = qualified_name

    @property
    def process_ref(self):
        """
        Gets the process_ref of this ProcessRunPK.
        Reference to a data activity/process, e.g. `credit_score_job`

        :return: The process_ref of this ProcessRunPK.
        :rtype: ProcessRef
        """
        return self._process_ref

    @process_ref.setter
    def process_ref(self, process_ref):
        """
        Sets the process_ref of this ProcessRunPK.
        Reference to a data activity/process, e.g. `credit_score_job`

        :param process_ref: The process_ref of this ProcessRunPK.
        :type: ProcessRef
        """
        if process_ref is None:
            raise ValueError("Invalid value for `process_ref`, must not be `None`")

        self._process_ref = process_ref

    @property
    def qualified_name(self):
        """
        Gets the qualified_name of this ProcessRunPK.
        Unique name by which this process run might be referred, e.g. `credit_score_job_app_123_1234`

        :return: The qualified_name of this ProcessRunPK.
        :rtype: str
        """
        return self._qualified_name

    @qualified_name.setter
    def qualified_name(self, qualified_name):
        """
        Sets the qualified_name of this ProcessRunPK.
        Unique name by which this process run might be referred, e.g. `credit_score_job_app_123_1234`

        :param qualified_name: The qualified_name of this ProcessRunPK.
        :type: str
        """
        if qualified_name is None:
            raise ValueError("Invalid value for `qualified_name`, must not be `None`")

        self._qualified_name = qualified_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ProcessRunPK):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
