# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat

from six import iteritems


class SchemaPK(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data_source_ref': 'DataSourceRef',
        'fields': 'list[FieldDef]'
    }

    attribute_map = {
        'data_source_ref': 'dataSourceRef',
        'fields': 'fields'
    }

    def __init__(self, data_source_ref=None, fields=None):
        """
        SchemaPK - a model defined in Swagger
        """

        self._data_source_ref = None
        self._fields = None

        self.data_source_ref = data_source_ref
        self.fields = fields

    @property
    def data_source_ref(self):
        """
        Gets the data_source_ref of this SchemaPK.
        A datasource where given schema was observed

        :return: The data_source_ref of this SchemaPK.
        :rtype: DataSourceRef
        """
        return self._data_source_ref

    @data_source_ref.setter
    def data_source_ref(self, data_source_ref):
        """
        Sets the data_source_ref of this SchemaPK.
        A datasource where given schema was observed

        :param data_source_ref: The data_source_ref of this SchemaPK.
        :type: DataSourceRef
        """
        if data_source_ref is None:
            raise ValueError("Invalid value for `data_source_ref`, must not be `None`")

        self._data_source_ref = data_source_ref

    @property
    def fields(self):
        """
        Gets the fields of this SchemaPK.
        Schema definition

        :return: The fields of this SchemaPK.
        :rtype: list[FieldDef]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """
        Sets the fields of this SchemaPK.
        Schema definition

        :param fields: The fields of this SchemaPK.
        :type: list[FieldDef]
        """
        if fields is None:
            raise ValueError("Invalid value for `fields`, must not be `None`")

        self._fields = fields

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SchemaPK):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
